#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_test_number:
    path: /test/number
    controller: App\Controller\TestController::number

app_test_numbertwig:
    path: /test/numbertwig
    controller: App\Controller\TestController::numbertwig
